### ISSUE TITLE
Question: what is the purpose of the Anchor Platform?

### ISSUE THREAD

**Issue by yuriescl** [stellar/stellar-disbursement-platform-backend#41]
I've been testing the SDP disbursement flows and noticed that the Anchor Platform is a requirement (it collects the phone number, verification, date of birth, etc), but the Anchor Platform does not fund the receiver wallet.
Just want to get some clarification on what's the role of the Anchor Platform in regards to SDP.

1) Is the purpose of the Anchor just to collect info (via SEP-24) and then associate the wallet pubkey with the SDP receiver in SDP?
2) If the Anchor does not fund (create account) the destination (receiver) wallet, which software is responsible for the funding? Assuming I don't to use Vibrant, do I have to setup a custom software to do the funding?

**Comment by reecexlm** [comment]
Thanks for your question, @yuriescl!

The Anchor Platform plays a vital role in ensuring the interoperability of wallet apps with the Stellar Disbursement Platform. As you've noted, the primary responsibility of the AP within the SDP framework is to gather essential recipient details through the SEP-24 deposit process. Once this information is collected, it is relayed to the SDP, which in turn facilitates the payment to the receiver. 

To illustrate the process further:
1. The payer initiates the disbursement.
2. The SDP dispatches an SMS containing a link with instructions.
3. The receiver accesses the link, leading to the installation of the wallet application. This acts as a deep link, opening the wallet app directly into the SEP-24 deposit flow.
4. The SEP-24 deposit flow begins: The SDP (via SEP-1) authenticates the wallet's public address (via SEP-10) and confirms the details and OTP through SEP-24.
5. The SDP registers the wallet's pubkey with the receiver.
6. Finally, the SDP transfers the payment to the receiver's wallet.

I hope this clarifies the process for you. If you have any more questions, please don't hesitate to ask. You can also refer to the [official docs](https://developers.stellar.org/docs/category/use-the-stellar-disbursement-platform) for a comprehensive understanding of the role of SEP-24. A point to note: there's no need to install the anchor-platform separately. The SDP exclusively uses the SEP service, which is integrated into the SDP helm chart (should you be using Kubernetes).

**Comment by yuriescl** [comment]
Thanks for the clarification. We got SDP working with AP and have setup a custom funding server for our use case. It's all working now, thank you.
