### ISSUE TITLE
dev/main.sh crashes if no jq or docker

### ISSUE THREAD

**Issue by papaben** [stellar/stellar-disbursement-platform-backend#421]
### What version are you using?
HEAD at b7c47bdc12bd3383259bd341642f4aa1c14c9539

### What did you do?
Followed `dev/README.md` instructions for running `dev/main.sh`

### What happened?
`jq` not found

### What did you expect to see instead?
Success =)

**Comment by marwen-abid** [comment]
Thank you @papaben for your contribution. This change will be available in version 3.0.0.
