### ISSUE TITLE
Docker Start up issue

### ISSUE THREAD

**Issue by tendemo1** [stellar/stellar-disbursement-platform-backend#54]
Hi started the backend with a docker image using "docker run -d -p 8080:8080 stellar/stellar-disbursement-platform-backend
" docker ps -a show that it was exited . How do I get around to troubleshoot the issue.

**Comment by marwen-abid** [comment]
Hi! Starting the stellar-disbursement-platform-backend requires some configuration as well as other dependencies to be running. Did you check our guide ? https://developers.stellar.org/docs/stellar-disbursement-platform/getting-started#run-the-sdp-locally

**Comment by reecexlm** [comment]
hi @tendemo1 .  We are going to close this issue. Please let us know if you still have further questions!
