### ISSUE TITLE
Feature Request: allow adding custom wallet providers

### ISSUE THREAD

**Issue by yuriescl** [stellar/stellar-disbursement-platform-backend#68]
Right now the default wallet providers are hardcoded. There should be a mechanism that allow easily adding/removing wallet providers:

![image](https://github.com/stellar/stellar-disbursement-platform-backend/assets/26092447/6638bf98-4652-494a-80ce-a59e052a21a5)

Also, it would be interesting to have a standard for the SDP interactions (Wallet <-> SDP and SDP <-> Anchor). Maybe a new SEP, not sure. This would allow custom wallets to easily integrate with SDP.

**Comment by yuriescl** [comment]
Just found this page but couldn't find an option to Add a new Wallet provider:

![image](https://github.com/stellar/stellar-disbursement-platform-backend/assets/26092447/26a2c702-5c58-4ca6-9fe8-9110076ab395)

There seems to be an API endpoint exactly for this:
![image](https://github.com/stellar/stellar-disbursement-platform-backend/assets/26092447/17d25301-4a53-41ee-b27c-cdc8508cf327)

So actually the feature would be to just add a UI to consume this endpoint

**Comment by reecexlm** [comment]
Thank you for your contribution!
